image:
  repository: ghcr.io/cristian98149/kcmsu
  tag: ""
  pullPolicy: IfNotPresent

cronjob:
  schedule: "*/1 * * * *"  # Cron schedule for job execution
  jobName: kcmsu

# Namespaces to be scanned by the tool
# namespaces:
#   - kube-system
#   - default

serviceAccount:
  create: true
  name: kcmsu
  namespace: default

rbac:
  create: true
  clusterRole:
    name: kcmsu-clusterrole
