{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRole.name }}
rules:
  # Permissions for listing Pods across the entire cluster
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # Permissions for listing Namespaces across the entire cluster
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # Permissions for listing Secrets across the entire cluster
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  # Permissions for listing ConfigMaps across the entire cluster
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
{{- end }}
