name: Build and Push Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Build Helm Chart
        run: helm package ./chart

      - name: Authenticate to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Helm Chart to GHCR
        run: helm push ./kcmsu-chart-*.tgz oci://ghcr.io/${{ github.actor }}
